### PR TITLE
Add www connection support

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by paramt** [comment]
[As far as I'm aware, there cannot be more than 1 entry in a CNAME file](https://help.github.com/en/articles/troubleshooting-custom-domains#multiple-domains-in-cname-file). Plus, www.1pt.co already redirects to 1pt.co, which is preferred for SEO anyways

**Comment by RDIL** [comment]
You can have two if the second one is just a www of the first

**Comment by paramt** [comment]
Hmm, but will that not just hurt the SEO by splitting it?

**Comment by RDIL** [comment]
Shouldn't be that different
more important pr: https://github.com/paramt/memeadvisor/pulls

**Pull request closed without merging**
